version: "3"

tasks:
  default:
    cmds:
      - task: run
  init:
    cmds:
      - task: clean
      - dart create app
  fmt:
    dir: app
    cmds:
      - dart format **/*.dart
  vet:
    dir: app
    cmds:
      - dart analyze
  run:
    dir: app
    cmds:
      - dart run
    silent: true
  clean:
    cmds:
      - rm -rf app

